<a href="https://colab.research.google.com/github/sush67/Deep-Learning-Essentials-Five-pillars-of-pytorch/blob/main/Deep%20Learning%20Essentials-Five%20pillars%20of%20pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning Essentials:Five pillars of pytorch

An short introduction about PyTorch and about the chosen functions. 

- torch.reshape()
- torch.cat()
- torch.chunk()
- torch.mul()
- torch.reciprocal()

Before we begin, let's install and import PyTorch

In [45]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1HfvnEKeJMp9rIDtiNem2czznjazG7fBJ')

In [46]:
# Import torch and other required modules
import torch
import jovian

## Function 1 - TORCH.RESHAPE

1. Returns a tensor with the same data and number of elements as input, but with the specified shape. 
2. When possible, the returned tensor will be a view of input. Otherwise, it will be a copy.
3. Contiguous inputs and inputs with compatible strides can be reshaped without copying, but you should not depend on the copying vs. viewing behavior.

**Syntax :**

torch.reshape(input, shape) → Tensor


**Parameters**

1. input (Tensor) – the tensor to be reshaped
2. shape (tuple of python:ints) – the new shape

Below we have initialized tensor2 with some random numbers and we are tring to reshape it by passing into the torch.reshape().

In [47]:
# Example 1 - working 
tensor2 = torch.tensor([[1, 2], [3, 4.]])
tensor2

tensor([[1., 2.],
        [3., 4.]])

In [48]:
tensor_reshaped = tensor2.reshape(1, 4)
tensor_reshaped

tensor([[1., 2., 3., 4.]])

In [49]:
# Example 2 - working
tensor_reshaped_2 = tensor2.reshape(1, -1)

In [50]:
tensor_reshaped_2

tensor([[1., 2., 3., 4.]])

Note that a single dimension may be -1, in which case it’s inferred from the remaining dimensions and the number of elements in input.

In [51]:
# Example 3 - breaking (to illustrate when it breaks)
tensor2.reshape(1, 5)


RuntimeError: ignored

The specified dimensions should be valid given the orginal input.

We are getting an error here because there are only 4 elements but we are asking to distribute it into one row and 5 columns, which is not possible.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='Deep Learning Essentials:Five pillars of pytorch')

## Function 2 - TORCH.CAT

1. Concatenates the given sequence of seq tensors in the given dimension.

2. All tensors must either have the same shape (except in the concatenating dimension) or be empty.

**Syntax :**

torch.cat(tensors, dim=0, *, out=None) → Tensor

**Parameters**

tensors (sequence of Tensors) – any python sequence of tensors of the same type. Non-empty tensors provided must have the same shape, except in the cat dimension.

dim (int, optional) – the dimension over which the tensors are concatenated

Below, We have intialized the tensor of shape 2x3 with random values and we  are trying to concatenate x with itself.

In [ ]:
# Example 1 - working
x = torch.randn(2, 3)
x
torch.cat((x, x, x), 0)

In [ ]:
# Example 2 - working
torch.cat((x, x, x), 1)

By chaning the dim parameters, the concatenation can be achieved along columns

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
tensor3 = torch.tensor([[1, 2], [3, 4.]])
tensor4 = torch.tensor([[2, 4], [6, 8.]])
tensor5 = torch.tensor([[2, 4, 6], [6, 8., 10]])
print(tensor3)
print(tensor4)
print(tensor5)

In [ ]:
torch.cat((tensor3, tensor4))

In [ ]:
torch.cat((tensor3, tensor4, tensor5))

The error is given by the fact that the shape of the last tensor is (2, 3), thus by concatenating along dimension 0 (vertically), the number of columns won't match.

If we were concatenating with dim=1, everything would be fine since tensors sizes match except the concatenating dimension.

In [ ]:
torch.cat((tensor3, tensor4, tensor5),dim=1)

torch.cat() can be seen as an inverse operation for torch.split() and torch.chunk()

In [ ]:
jovian.commit(project='Deep Learning Essentials:Five pillars of pytorch')

## Function 3 - TORCH.CHUNK

Splits a tensor into a specific number of chunks. Each chunk is a view of the input tensor.

**Syntax :**

torch.chunk(input, chunks, dim=0) → List of Tensors

**Parameters**

input (Tensor) – the tensor to split

chunks (int) – number of chunks to return, which is to be a positive integer.

dim (int) – dimension along which to split the tensor

Here we have splitted chunkedt1 into 2 chunks.

In [ ]:
# Example 1 - working
t1 = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
t1


In [ ]:
chunkedt1 = t1.chunk(2)
chunkedt1

In [ ]:
chunkedt1[0]

In [ ]:
chunkedt1[1]

In [ ]:
# Example 2 - working
chunkedt1 = t1.chunk(10)
chunkedt1
print("length of chunkedt1 is:{}".format(len(chunkedt1)))

It can be observed thatlength of chunkedt1 is 6.

What just happened?!! 

We asked for 10 chunks, by disecting the tensor, pytorch returns the highest number of chuncks it can possibly grab.

This is how torch.chunk() works!

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
t1.chunk(-1)

In [ ]:
t1.chunk(1.4)

Note that ,we can't pass in negative numbers or float value as a chunk value parameter, it accepts only integers and numbers greater than 0

torch.chunk() is pretty usefull when we are working with tensors and trying get subarray from it.

In [ ]:
jovian.commit(project='Deep Learning Essentials:Five pillars of pytorch')

## Function 4 - TORCH.MUL

Multiplies each element of the input input with the scalar other and returns a new resulting tensor.



**Syntax :**

torch.mul(input, other, *, out=None)

**Parameters**

{input} –

other (Number) – the number to be multiplied to each element of input or another tensor

If input is of type FloatTensor or DoubleTensor, other should be a real number, otherwise it should be an integer

In [ ]:
# Example 1 - working
a = torch.randn(5)
a
torch.mul(a, 100)

Observe that each element of the tensor input is multiplied by the corresponding element of the Tensor other. The resulting tensor is returned.

In [ ]:
# Example 2 - working
a = torch.randn(5, 1)
a

In [ ]:
b = torch.randn(1, 5)
b

In [ ]:
torch.mul(a, b)

The shapes of input and other must be broadcastable

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
c = torch.rand(1,6)
c

In [ ]:
torch.mul(b,c)

Error is raised when the size of the tensors are not compatible with each other.

torch.mul() is really useful when we are performing complex mathematical operations and calculations.

In [ ]:
jovian.commit(project='Deep Learning Essentials:Five pillars of pytorch')

## Function 5 - TORCH.BERNOULLI

Draws binary random numbers (0 or 1) from a Bernoulli distribution.

The input tensor should be a tensor containing probabilities to be used for drawing the binary random number.Hence, all values in input have to be in the range: 0<=input<=1

The output tensor only has values 0 or 1 and is of the same shape as input.

**Syntax :**

torch.bernoulli(input, *, generator=None, out=None) → Tensor

**Parameters**

input (Tensor) – the input tensor of probability values for the Bernoulli distribution

In [ ]:
# Example 1 - working
d = torch.empty(3, 3).uniform_(0, 1) 
d

In [ ]:
torch.bernoulli(d)

We have intialized tensor d with some values using uniform_()and the respective output is as shown above.

In [ ]:
# Example 2 - working
e = torch.empty(4, 3).uniform_(0, 1) 
e

In [ ]:
torch.bernoulli(e)

This example is similar to the above one except the fact that this is not a tensor with equal no. of rows and columns.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
f = torch.empty(3, 3).uniform_(0,2)
print(f)


In [ ]:
torch.bernoulli(f)

Strictly,the range of the input tensor should be in range of [0,1],else the whole Bernoulli distribution, itself becomes wrong!

In [ ]:
jovian.commit(project='Deep Learning Essentials:Five pillars of pytorch')

## Conclusion

We have seen the 5 interesting functions and their
1.   Description
2.   Syntax
3.   Parameters
5.   Working- using examples
6.   When the function breaks/raises errors

There are lot of functions in pytorch which are essential and fun to work with. Explore all of them using the reference link provided below.

I hope this short introduction is helpful!

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html

In [ ]:
jovian.commit(project='Deep Learning Essentials:Five pillars of pytorch')